# Generated by Django 4.0.3 on 2022-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('bb_min', models.IntegerField()),
                ('bb_max', models.IntegerField()),
            ],
            options={
                'db_table': 'bb_model',
            },
        ),
    ]
